# Generated by Django 4.2.4 on 2023-08-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='task_title')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete')),
            ],
        ),
    ]
