# Generated by Django 4.2.4 on 2023-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='task title')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
