# Generated by Django 4.2.4 on 2023-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_options_task_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_postponed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('postponed', 'Postponed')], default='in_progress', max_length=11),
        ),
    ]
