# Generated by Django 4.2.4 on 2023-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_task_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_last_modified',
            new_name='date_updated',
        ),
    ]
