# Generated by Django 4.2.4 on 2023-12-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_created']},
        ),
    ]
